# file: .github/workflows/show-directory.yml
name: say-hello
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v4
      - run: make say-hello